pages:
  image: registry.gitlab.com/gbraad/byo-atomic-toolbox:f25 
  script:
  - ./compose.sh
  - mv /srv/repo public
  - cp index.html ./public
  artifacts:
    paths:
    - public
  only:
    - master

build_image_toolbox:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/byo-atomic-fedora:tb25 -f Dockerfile.toolbox .
    - docker push registry.gitlab.com/gbraad/byo-atomic-fedora:tb25
  only:
    - master

build_image_fedora:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/byo-atomic-fedora:25 .
    - docker push registry.gitlab.com/gbraad/byo-atomic-fedora:25
  only:
    - master
