#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: Clone Fedora-Atomic buildscripts
    git: >-
      repo=https://git.fedorahosted.org/git/fedora-atomic.git
      version=f23
      depth=1
      dest=/home/working/fedora-atomic

  - name: Compose Fedora-Atomic tree
    command: >-
      chdir=/home/working/fedora-atomic/
      rpm-ostree compose tree --repo=/srv/repo ./fedora-atomic-docker-host.json
