#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: Clone Fedora-Atomic buildscripts
    git: >-
      repo=https://pagure.io/fedora-atomic.git
      version=f25
      depth=1
      dest=/workspace/fedora-atomic

  - name: Compose Fedora-Atomic tree
    command: >-
      chdir=/workspace/fedora-atomic/
      rpm-ostree compose tree --repo=/srv/repo ./fedora-atomic-docker-host.json
