FROM registry.gitlab.com/gbraad/byo-atomic-toolbox:f25
MAINTAINER Gerard Braad <me@gbraad.nl>

ADD ./compose.sh /workspace
RUN cd /workspace && ./compose.sh

EXPOSE 8000
WORKDIR /workspace

CMD ostree trivial-httpd -p 8000 /srv/repo
